### ISSUE TITLE
MDBForm an on:submit

### ISSUE THREAD

**Issue by pspierce** [mdbootstrap/mdbsvelte#11]
I just quite figure out how you are supposed to capture the submit.  I looked through utils.js at the relevant forwarding events stuff but I'm at a loss on how you are using it.  I was hoping to see something in the storybook/examples/dashboard but no such luck.

Using MDBFormInline, how do I capture the submit event?

**Comment by SauravKanchan** [comment]
I have added the submit events now, upgrade the package, and try again.
